{% set name = "expecttest" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expecttest-{{ version }}.tar.gz
  sha256: e52b1cf8a6f84506e6962a0bbdd248ea442124d826e849f263ec1c322ebb73f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - expecttest

about:
  home: https://github.com/ezyang/expecttest
  summary: Expect tests for unittest
  description: |
    This library implements expect tests (also known as "golden" tests). Expect tests
    are a method of writing tests where instead of hard-coding the expected output of
    a test, you run the test to get the output, and the test framework automatically
    populates the expected output. If the output of the test changes, you can rerun the
    test with the environment variable EXPECTTEST_ACCEPT=1 to automatically update the
    expected output.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ezyang
    - pmeier
