{% set name = "expecttest" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/expecttest-{{ version }}.tar.gz
  sha256: 6e8512fb86523ada1f94fd1b14e280f924e379064bb8a29ee399950e513eeccd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - expecttest

about:
  home: https://github.com/ezyang/expecttest
  summary: Expect tests for unittest
  description: |
    This library implements expect tests (also known as "golden" tests). Expect tests
    are a method of writing tests where instead of hard-coding the expected output of
    a test, you run the test to get the output, and the test framework automatically
    populates the expected output. If the output of the test changes, you can rerun the
    test with the environment variable EXPECTTEST_ACCEPT=1 to automatically update the
    expected output.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ezyang
    - pmeier
